# Generated by Django 5.2.3 on 2025-06-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_recordings/')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
