# Generated by Django 5.2.3 on 2025-06-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AudioRecording',
            new_name='RecordedAudio',
        ),
        migrations.RenameField(
            model_name='recordedaudio',
            old_name='recorded_at',
            new_name='uploaded_at',
        ),
    ]
