# Generated by Django 5.2.3 on 2025-06-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_rename_audiorecording_recordedaudio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecordedAudio',
            new_name='AudioRecording',
        ),
        migrations.RenameField(
            model_name='audiorecording',
            old_name='uploaded_at',
            new_name='recorded_at',
        ),
    ]
