# Generated by Django 5.2.3 on 2025-07-08 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_rename_recordedaudio_audiorecording_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecording',
            name='text_from_audio',
            field=models.TextField(blank=True, default='', verbose_name='text fron audio'),
        ),
        migrations.AlterField(
            model_name='audiorecording',
            name='audio_file',
            field=models.FileField(upload_to='audio_recordings/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav'])], verbose_name='Аудиофайл'),
        ),
    ]
