# Generated by Django 5.2.3 on 2025-07-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_audiorecording_text_from_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecording',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
