# Generated by Django 5.2.3 on 2025-07-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_audiorecording_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecordingJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='audiorecording',
            name='data',
        ),
    ]
