# Generated by Django 5.2.3 on 2025-07-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_audiorecordingjson_remove_audiorecording_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecordingjson',
            name='author',
            field=models.CharField(default='None', max_length=25, verbose_name='Autor'),
        ),
    ]
