# Generated by Django 5.2.3 on 2025-07-11 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0007_audiorecordingjson_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecordingjson',
            name='audio_file',
            field=models.FileField(default=None, upload_to='audio_case/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav'])], verbose_name='Аудиофайл'),
        ),
    ]
