# Generated by Django 5.2.3 on 2025-07-12 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0008_audiorecordingjson_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecordingjson',
            name='text_from_audio',
            field=models.TextField(blank=True, default='', verbose_name='text fron audio'),
        ),
        migrations.AlterField(
            model_name='audiorecordingjson',
            name='audio_file',
            field=models.FileField(default='audio_case/', upload_to='audio_case/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav'])], verbose_name='Аудиофайл'),
        ),
    ]
