# Generated by Django 5.2.3 on 2025-07-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0009_audiorecordingjson_text_from_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecordingjson',
            name='id_data',
            field=models.CharField(default='', max_length=23),
        ),
    ]
