# Generated by Django 5.2.3 on 2025-06-28 17:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='None', max_length=25, verbose_name='First name')),
                ('surname', models.CharField(blank=True, default='None', max_length=25, verbose_name='Surname')),
                ('last_name', models.CharField(blank=True, default='None', max_length=25, verbose_name='Last name')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Вate of birth')),
                ('code_patient', models.CharField(blank=True, max_length=25, null=True)),
                ('author', models.OneToOneField(blank=True, max_length=25, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='patient')),
            ],
        ),
    ]
