# Generated by Django 5.2.3 on 2025-06-29 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_alter_patient_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='author',
            field=models.CharField(default='None', max_length=25, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Вate of birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='имя', max_length=25, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='фамилия', max_length=25, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='surname',
            field=models.CharField(blank=True, default='отчество', max_length=25, verbose_name='Surname'),
        ),
    ]
