# Generated by Django 5.2.3 on 2025-06-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='users/profile_images/%Y/%m/%d/', verbose_name='Photo user'),
        ),
    ]
