# Generated by Django 5.2.3 on 2025-06-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='users/profile_images/%Y/%m/%d/', verbose_name='Photo user', width_field=300),
        ),
    ]
