# Generated by Django 5.2.3 on 2025-06-27 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_images/%Y/%m/%d/', verbose_name='аватар - '),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('RU', 'RUS'), ('BY', 'BLR')], default='RU', max_length=3)),
                ('town', models.CharField(blank=True, default='-пусто-', max_length=254, null=True, verbose_name='Town')),
                ('RVC', models.CharField(blank=True, default='-пусто-', max_length=254, null=True, verbose_name='Regional Vascular Center')),
                ('PVD', models.CharField(blank=True, default='-пусто-', max_length=254, null=True, verbose_name='Primary vascular department')),
                ('medical_organization', models.CharField(blank=True, default='-пусто-', max_length=254, null=True, verbose_name='medical organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='job')),
            ],
        ),
    ]
