# Generated by Django 5.2.3 on 2025-06-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_photo_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='user_job',
        ),
    ]
