# Generated by Django 5.2.3 on 2025-06-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_user_job_user_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user_job',
            new_name='user',
        ),
    ]
