# Generated by Django 5.2.3 on 2025-06-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_user_job_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(choices=[('RU', 'Россия'), ('BY', 'Белорусия')], default='RU', max_length=3),
        ),
    ]
