# Generated by Django 5.2.3 on 2025-06-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_job_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='user_job',
        ),
    ]
