# Generated by Django 5.2.3 on 2025-06-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_user_job_job_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='PVD',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Primary vascular department'),
        ),
        migrations.AlterField(
            model_name='job',
            name='RVC',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Regional Vascular Center'),
        ),
        migrations.AlterField(
            model_name='job',
            name='medical_organization',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='medical organization'),
        ),
        migrations.AlterField(
            model_name='job',
            name='town',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Town'),
        ),
    ]
